stages:
  - deploy
  - deploy

before_script:
  - export LAST_ROOT_NAMESPACE="$(echo $CI_PROJECT_NAMESPACE | rev | cut -d'/' -f1 | rev)"
  - export NAMESPACE_BASED_BRANCH="${LAST_ROOT_NAMESPACE}-test"
  - if [ $CI_COMMIT_REF_NAME = "main" ]; then export NAMESPACE_BASED_BRANCH="${LAST_ROOT_NAMESPACE}"; fi
  - export TAG="$CI_COMMIT_REF_SLUG-$(echo $CI_COMMIT_TIMESTAMP | cut -c1-10)-$CI_COMMIT_SHORT_SHA"
  - export HOME_DIR="/app/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  - echo "Namespace for build - ${NAMESPACE_BASED_BRANCH}"

deploy to dev server:
  stage: deploy
  stage: deploy
  tags:
    - kulenkov
    - dev
    - ps
  script:
    - echo "# Deploy Stage start"
    - echo "update project in $HOME_DIR"
    - git -C $HOME_DIR reset --hard
    - git -C $HOME_DIR checkout -- .
    - git -C $HOME_DIR pull origin ${CI_COMMIT_BRANCH}
    - cd $HOME_DIR
    - sed -i 's/SERVICE_IMAGE_TAG=.*/SERVICE_IMAGE_TAG='${TAG}'/' $HOME_DIR/.env.docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #    - docker pull ${CI_REGISTRY_IMAGE}:${TAG}
    #    - docker stop ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    #    - docker rm ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    - docker-compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml down
    - docker-compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml up -d
    - docker system prune -a -f
    - echo "# Deploy Stage end"
  only:
    - dev

deploy to prod server:
  stage: deploy
  tags:
    - lawyerplace
    - prod
    - pskz
  when: manual
  script:
    - echo "# Deploy Stage start"
    - echo "update project in $HOME_DIR"
    - git -C $HOME_DIR reset --hard
    - git -C $HOME_DIR checkout -- .
    - git -C $HOME_DIR pull origin ${CI_COMMIT_BRANCH}
    - cd $HOME_DIR
    - sed -i 's/SERVICE_IMAGE_TAG=.*/SERVICE_IMAGE_TAG='${TAG}'/' $HOME_DIR/.env.docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #    - docker pull ${CI_REGISTRY_IMAGE}:${TAG}
    #    - docker stop ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    #    - docker rm ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    - docker compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml down
    - docker compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml up -d
    - docker system prune -a -f
    - docker exec nginx nginx -s reload
    - echo "# Deploy Stage end"
  only:
    - dev

deploy to prod server:
  stage: deploy
  tags:
    - lawyerplace
    - prod
    - pskz
  when: manual
  script:
    - echo "# Deploy Stage start"
    - echo "update project in $HOME_DIR"
    - git -C $HOME_DIR reset --hard
    - git -C $HOME_DIR checkout -- .
    - git -C $HOME_DIR pull origin ${CI_COMMIT_BRANCH}
    - cd $HOME_DIR
    - sed -i 's/SERVICE_IMAGE_TAG=.*/SERVICE_IMAGE_TAG='${TAG}'/' $HOME_DIR/.env.docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #    - docker pull ${CI_REGISTRY_IMAGE}:${TAG}
    #    - docker stop ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    #    - docker rm ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    - docker compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml down
    - docker compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml up -d
    - docker system prune -a -f
    - docker exec nginx nginx -s reload
    - echo "# Deploy Stage end"
  only:
    - dev

deploy to prod server:
  stage: deploy
  tags:
    - lawyerplace
    - prod
    - pskz
  when: manual
  script:
    - echo "# Deploy Stage start"
    - echo "update project in $HOME_DIR"
    - git -C $HOME_DIR reset --hard
    - git -C $HOME_DIR checkout -- .
    - git -C $HOME_DIR pull origin ${CI_COMMIT_BRANCH}
    - cd $HOME_DIR
    - sed -i 's/SERVICE_IMAGE_TAG=.*/SERVICE_IMAGE_TAG='${TAG}'/' $HOME_DIR/.env.docker-compose
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #    - docker pull ${CI_REGISTRY_IMAGE}:${TAG}
    #    - docker stop ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    #    - docker rm ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME}
    - docker compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml down
    - docker compose -p ${LAST_ROOT_NAMESPACE}_${CI_PROJECT_NAME} --env-file $HOME_DIR/.env.docker-compose -f $HOME_DIR/docker-compose.yml up -d
    - docker system prune -a -f
    - echo "# Deploy Stage end"
  only:
    - main