version: '3.5'

services:
  lawyerplace-frontend:
    container_name: lawyerplace-frontend
    image: ${SERVICE_IMAGE_NAME}:${SERVICE_IMAGE_TAG}
    build:
      context: .
      args:
        - "env_build=${SERVICE_PROFILE}"
      dockerfile: ./.docker/nextjs/Dockerfile
    restart: always
    networks:
      - lawyerplace_network
    env_file:
      - .env
    ports:
      - "3000:3000"  # 👈 теперь системный nginx увидит фронтенд

networks:
  lawyerplace_network:
    external: true
