version: '3.5'

services:
  lawyerplace-frontend:
    container_name: lawyerplace-frontend
    image: registry.gitlab.com/kulenkov1/lawyer-place/web-app:${SERVICE_IMAGE_TAG}
    restart: always
    networks:
      - lawyerplace_network
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  lawyerplace_network:
    external: true
