version: '3.5'

services:
    lawyerplace-frontend:
      image: ${SERVICE_IMAGE_NAME}:${SERVICE_IMAGE_TAG}
      build:
        context: .
        args:
          - "env_build=${SERVICE_PROFILE}"
        dockerfile: ./.docker/nextjs/Dockerfile
      restart: always
      container_name: lawyerplace-frontend
      networks:
        - lawyerplace-network
      env_file:
        - .env


networks:
  lawyerplace-network:
    external: true
