version: '3.5'

services:
  zanger-newfront:
    container_name: zanger-newfront
    image: ${SERVICE_IMAGE_NAME}:${SERVICE_IMAGE_TAG}
    restart: always
    networks:
      - lawyerplace_network
    ports:
      - "127.0.0.1:3001:3000"

networks:
  lawyerplace_network:
    external: true